### ISSUE TITLE
Development Installation Documentation outdated

### ISSUE THREAD

**Issue by BradPohl** [dataflownb/dfnotebook-extension#37]
> jupyter labextension develop . --overwrite

This command throws errors when following documentation currently. It seems like it should be replaced with jlpm install then continuing with normal documentation.

**Comment by dakoop** [comment]
Ok, just tested. When I run this:
```
mkdir dfnotebook
cd dfnotebook
git clone git@github.com:dataflownb/dfnotebook-extension.git
git clone git@github.com:dataflownb/dfkernel.git
mamba create --name dfnb -y jupyterlab ipykernel
mamba activate dfnb
cd dfkernel
pip install -e .
cd ..
cd dfnotebook-extension
pip install -e .
cd ..
jupyter lab
```
I see the following when running a cell using the dfkernel:
```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/dakoop/Applications/mambaforge/envs/dfnb/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/Users/dakoop/Research/dataflownb/dfnotebook/dfkernel/dfkernel/ipkernel.py", line 113, in execute_request
    res = await self.inner_execute_request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dakoop/Research/dataflownb/dfnotebook/dfkernel/dfkernel/ipkernel.py", line 179, in inner_execute_request
    dfkernel_data["code_dict"][uuid] = code
    ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'code_dict'
```
When I modify my process to do
```
mkdir dfnotebook
cd dfnotebook
git clone git@github.com:dataflownb/dfnotebook-extension.git
git clone git@github.com:dataflownb/dfkernel.git
mamba create --name dfnb -y jupyterlab ipykernel
mamba activate dfnb
cd dfkernel
pip install -e .
cd ..
cd dfnotebook-extension
jlpm install
jlpm build
pip install -e .
cd ..
jupyter lab
```
things seem to be ok. Not sure if this is expected or if the `pip install -e .` needs to do more.

**Comment by dakoop** [comment]
`jupyter labextension develop . --overwrite` likely fails because there was no labextension directory created because the build was not run

**Comment by dakoop** [comment]
We still need to run the develop command after a `pip install -e .` as far as I can tell. If I add the `jlpm develop` call into the editable build script, I get an error about metadata

```
  Traceback (most recent call last):
    File "/Users/dakoop/Applications/mambaforge/envs/dfnb/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 167, in prepare_metadata_for_build_editable
      hook = backend.prepare_metadata_for_build_editable
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_editable'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/Users/dakoop/Applications/mambaforge/envs/dfnb/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/dakoop/Applications/mambaforge/envs/dfnb/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/dakoop/Applications/mambaforge/envs/dfnb/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 176, in prepare_metadata_for_build_editable
      whl_basename = build_hook(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/4f/hdnf7bzs0ng2pg652ppm9sv80000gn/T/pip-build-env-xlq8b0dg/overlay/lib/python3.12/site-packages/hatchling/build.py", line 83, in build_editable
      return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/4f/hdnf7bzs0ng2pg652ppm9sv80000gn/T/pip-build-env-xlq8b0dg/overlay/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 147, in build
      build_hook.initialize(version, build_data)
    File "/private/var/folders/4f/hdnf7bzs0ng2pg652ppm9sv80000gn/T/pip-build-env-xlq8b0dg/normal/lib/python3.12/site-packages/hatch_jupyter_builder/plugin.py", line 94, in initialize
      raise e
    File "/private/var/folders/4f/hdnf7bzs0ng2pg652ppm9sv80000gn/T/pip-build-env-xlq8b0dg/normal/lib/python3.12/site-packages/hatch_jupyter_builder/plugin.py", line 89, in initialize
      build_func(self.target_name, version, **build_kwargs)
    File "/private/var/folders/4f/hdnf7bzs0ng2pg652ppm9sv80000gn/T/pip-build-env-xlq8b0dg/normal/lib/python3.12/site-packages/hatch_jupyter_builder/utils.py", line 117, in npm_builder
      run([*npm_cmd, "run", build_cmd], cwd=str(abs_path))
    File "/private/var/folders/4f/hdnf7bzs0ng2pg652ppm9sv80000gn/T/pip-build-env-xlq8b0dg/normal/lib/python3.12/site-packages/hatch_jupyter_builder/utils.py", line 231, in run
      return subprocess.check_call(cmd, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/dakoop/Applications/mambaforge/envs/dfnb/lib/python3.12/subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/private/var/folders/4f/hdnf7bzs0ng2pg652ppm9sv80000gn/T/pip-build-env-xlq8b0dg/overlay/bin/jlpm', 'run', 'build:dev']' returned non-zero exit status 1.
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
```
There are some suggestions about setting `allow-direct-references` (<https://stackoverflow.com/a/73332363>), but this doesn't seem to help. I think the core issue is that the build occurs in a separate env and the symlinks that develop adds cannot be added until after the build.
